### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by florinel-chis** [tzyganu/moduleCreator#1]
Got the following error when saving:

`app/code/community/Ultimate/ModuleCreator/etc/modulecreator/app/code/codepool/Namespace/Module/sql/namespace_module_setup/mysql4-install-0.0.1/01_top.php): failed to open stream`

I belive some files are missing.

**Comment by tzyganu** [comment]
This was because of the default .gitignore file.
Removed restriction on 'sql' and added files:
app/code/community/Ultimate/ModuleCreator/etc/modulecreator/app/code/codepool/Namespace/Module/sql/namespace_module_setup/mysql4-install-0.0.1/01_top.php
app/code/community/Ultimate/ModuleCreator/etc/modulecreator/app/code/codepool/Namespace/Module/sql/namespace_module_setup/mysql4-install-0.0.1/02_entity.php
app/code/community/Ultimate/ModuleCreator/etc/modulecreator/app/code/codepool/Namespace/Module/sql/namespace_module_setup/mysql4-install-0.0.1/03_footer.php
